using System.Collections.Generic;

namespace TM3ClientExtension.Models
{
    public class HistoricalValuesKey
    {
        public Dictionary<string, string> kpis { get; set; }
        public string Name { get; set; }
        public string Key { get; set; }
        public string Description { get; set; }
        
            public static Dictionary<string, HistoricalValuesKey> KeyDictionary { get; } = new Dictionary<string, HistoricalValuesKey>
        {
            { "BC", new HistoricalValuesKey { Name = "Business Consultant", Key = "BC", Description = "Is a Business Consultant" } },
            { "RC", new HistoricalValuesKey { Name = "Retail Customer", Key = "RC", Description = "Is a Retail Customer" } },
            { "PC", new HistoricalValuesKey { Name = "Preferred Customer", Key = "PC", Description = "Is a Preferred Customer" } },
            { "CUST", new HistoricalValuesKey { Name = "Customer", Key = "CUST", Description = "Is a Customer" } },
            { "MBV", new HistoricalValuesKey { Name = "Manual Bonus", Key = "MBV", Description = "Manual Bonus Volume" } },
            { "QVw", new HistoricalValuesKey { Name = "Qualifying Volume (w)", Key = "QVw", Description = "Base QV in Current Week" } },
            { "QV4w", new HistoricalValuesKey { Name = "Qualifying Volume (4w)", Key = "QV4w", Description = "Base QV in 4-Wk Rolling" } },
            { "QVw100", new HistoricalValuesKey { Name = "QV Above 100 (w)", Key = "QVw100", Description = "QV above 100 in Current Week" } },
            { "QV4w100", new HistoricalValuesKey { Name = "QV Above 100 (4w)", Key = "QV4w100", Description = "QV above 100 in 4-Wk Rolling" } },
            { "QVlt", new HistoricalValuesKey { Name = "Lifetime QV (lt)", Key = "QVlt", Description = "Base QV Lifetime" } },
            { "CVw", new HistoricalValuesKey { Name = "Commissionable Volume (w)", Key = "CVw", Description = "Base CV in Current Week" } },
            { "CV4w", new HistoricalValuesKey { Name = "Commissionable Volume (4w)", Key = "CV4w", Description = "Base CV in 4-Wk Rolling" } },
            { "GROWw", new HistoricalValuesKey { Name = "Grow SKU Purchase (w)", Key = "GROWw", Description = "Grow SKU in Current Week" } },
            { "RQVw", new HistoricalValuesKey { Name = "Retail QV (w)", Key = "RQVw", Description = "QV from PE Customers" } },
            { "RQV4w", new HistoricalValuesKey { Name = "Retail QV (4w)", Key = "RQV4w", Description = "QV from PE Customers" } },
            { "RCVw", new HistoricalValuesKey { Name = "Retail CV (w)", Key = "RCVw", Description = "CV from PE Customers" } },
            { "PVw", new HistoricalValuesKey { Name = "PV (w)", Key = "PVw", Description = "QV from Self and PE Cust in Current Week" } },
            { "PV4w", new HistoricalValuesKey { Name = "PV (4w)", Key = "PV4w", Description = "QV from Self and PE Cust in 4-Wk Rolling" } },
            { "FOCVw", new HistoricalValuesKey { Name = "First Order CV (w)", Key = "FOCVw", Description = "First Order CV" } },
            { "GVw", new HistoricalValuesKey { Name = "Team Volume QV (w)", Key = "GVw", Description = "GV (No Personal) in Current Week" } },
            { "GV4w", new HistoricalValuesKey { Name = "Team Volume QV (4w)", Key = "GV4w", Description = "GV (No Personal) in 4-Wk Rolling" } },
            { "GVlt", new HistoricalValuesKey { Name = "Team Volume QV (lt)", Key = "GVlt", Description = "Lifetime GV (Downline Only)" } },
            { "GCVw", new HistoricalValuesKey { Name = "Enroller CV (w)", Key = "GCVw", Description = "Enroller CV (No Personal) in Weekly Period" } },
            { "GCV4w", new HistoricalValuesKey { Name = "Enroller CV (4w)", Key = "GCV4w", Description = "Enroller CV (No Personal) in 4-Wk Rolling" } },
            { "TGVw", new HistoricalValuesKey { Name = "Total Enroller QV (w)", Key = "TGVw", Description = "GV (w/Personal Above 100) in Current Week" } },
            { "TGV4w", new HistoricalValuesKey { Name = "Total Enroller QV (4w)", Key = "TGV4w", Description = "GV (w/Personal Above 100) in 4-Wk Rolling" } },
            { "BCQVlt", new HistoricalValuesKey { Name = "Business Consultant QV (lt)", Key = "BCQVlt", Description = "Lifetime QV (100%) + GV" } },
            { "BCQ", new HistoricalValuesKey { Name = "Business Consultant Qualified", Key = "BCQ", Description = "500 BCQV to Become a Business Consultant" } },
            { "QL", new HistoricalValuesKey { Name = "Qualified Leg (4w)", Key = "QL", Description = "Is a Qualified Leg (10PV in 4-Wk Rolling)" } },
            { "PEQLs", new HistoricalValuesKey { Name = "# of PE Qualified Legs (4w)", Key = "PEQLs", Description = "# of PE Qualified Legs in 4-Wk Rolling" } },
            { "CA4w", new HistoricalValuesKey { Name = "Commission Active (4w)", Key = "CA4w", Description = "100PV (me + cust) in 4-Wk Rolling" } },
            { "R50cp", new HistoricalValuesKey { Name = "Director Current Period", Key = "R50cp", Description = "Is a Director in Current Period?" } },
            { "R50ct", new HistoricalValuesKey { Name = "Director Count", Key = "R50ct", Description = "# of Times Achieved Rank of Director" } },
            { "R60cp", new HistoricalValuesKey { Name = "Sr. Director Current Period", Key = "R60cp", Description = "Is a Sr. Director in Current Period?" } },
            { "R60ct", new HistoricalValuesKey { Name = "Sr. Director Count", Key = "R60ct", Description = "# of Times Achieved Rank of Sr. Director" } },
            { "R70cp", new HistoricalValuesKey { Name = "Exec. Director Current Period", Key = "R70cp", Description = "Is an Exec. Director in Current Period?" } },
            { "R70ct", new HistoricalValuesKey { Name = "Exec. Director Count", Key = "R70ct", Description = "# of Times Achieved Rank of Exec. Director" } },
            { "R80cp", new HistoricalValuesKey { Name = "Vice President Current Period", Key = "R80cp", Description = "Is a Vice President in Current Period?" } },
            { "R80ct", new HistoricalValuesKey { Name = "Vice President Count", Key = "R80ct", Description = "# of Times Achieved Rank of Vice President" } },
            { "R90cp", new HistoricalValuesKey { Name = "Sr. Vice Pres Current Period", Key = "R90cp", Description = "Is a Sr. Vice President in Current Period?" } },
            { "R90ct", new HistoricalValuesKey { Name = "Sr. Vice Pres Count", Key = "R90ct", Description = "# of Times Achieved Rank of Sr. Vice Pres" } },
            { "R100cp", new HistoricalValuesKey { Name = "Pres. Board Memb Current Period", Key = "R100cp", Description = "Is a Pres Board Member in Current Period?" } },
            { "R100ct", new HistoricalValuesKey { Name = "Pres. Board Memb Count", Key = "R100ct", Description = "# of Times Achieved Rank of Pres. Board Member" } },
            { "R110cp", new HistoricalValuesKey { Name = "Chairman Current Period", Key = "R110cp", Description = "Is a Chairman in Current Period?" } },
            { "R110ct", new HistoricalValuesKey { Name = "Chairman Count", Key = "R110ct", Description = "# of Times Achieved Rank of Chairman" } },
            { "R120cp", new HistoricalValuesKey { Name = "Exec. Chairman Current Period", Key = "R120cp", Description = "Is a Exec. Chairman in Current Period?" } },
            { "R120ct", new HistoricalValuesKey { Name = "Exec. Chairman Count", Key = "R120ct", Description = "# of Times Achieved Rank of Exec. Chairman" } },
            { "R130cp", new HistoricalValuesKey { Name = "Crown Ambassador Current Period", Key = "R130cp", Description = "Is a Crown Ambassador in Current Period?" } },
            { "R130ct", new HistoricalValuesKey { Name = "Crown Ambassador Count", Key = "R130ct", Description = "# of Times Achieved Rank of Crown Ambassador" } },
            { "R140cp", new HistoricalValuesKey { Name = "Crown Diam Amb Current Period", Key = "R140cp", Description = "Is a Crown Diam Amb in Current Period?" } },
            { "R140ct", new HistoricalValuesKey { Name = "Crown Diam Amb Count", Key = "R140ct", Description = "# of Times Achieved Rank of Crown Diam Amb" } },
            { "PED", new HistoricalValuesKey { Name = "P.E. Members (4w)", Key = "PED", Description = "# of PE Members in Enroller Tree" } },
            { "PECUST", new HistoricalValuesKey { Name = "P.E. Customers (4w)", Key = "PECUST", Description = "# of PE Retail & Preferred Customers in Enroller Tree" } },
            { "PERC", new HistoricalValuesKey { Name = "P.E. Retail Customers (4w)", Key = "PERC", Description = "# of PE Retail Customers in Enroller Tree" } },
            { "PEPC", new HistoricalValuesKey { Name = "P.E. Preferred Customers (4w)", Key = "PEPC", Description = "# of PE Preferred Customers in Enroller Tree" } },
            { "GBpay", new HistoricalValuesKey { Name = "Grow Bonus Pay Volume (w)", Key = "GBpay", Description = "Grow Bonus Pay Volume" } },
            { "TBpay", new HistoricalValuesKey { Name = "Team Bonus Pay Volume (4w)", Key = "TBpay", Description = "Fixed Volume Pay" } },
            { "RUpay", new HistoricalValuesKey { Name = "Rank Up Pay Volume", Key = "RUpay", Description = "Rank Up Pay Volume" } }
        };
        public static Dictionary<string, string> DsHistoricalKeys = new Dictionary<string, string>
        {
            { "Name", "10WR100" },
            { "Name", "10WR90" },
            { "Name", "2Qual" },
            { "Name", "3Qual" },
            { "Name", "4Qual" },
            { "Name", "5Qual" },
            { "Name", "Active" },
            { "BC", "BC" },
            { "Name", "BC90" },
            { "Name", "BCCKPI" },
            { "Name", "CB" },
            { "Name", "COGVKPI" },
            { "Name", "ComAct" },
            { "Name", "COQual" },
            { "Name", "DRUP" },
            { "Name", "EDRUP" },
            { "Name", "FR100" },
            { "Name", "FR60" },
            { "Name", "FR70" },
            { "Name", "FR80" },
            { "Name", "FR90" },
            { "Name", "GVKPI" },
            { "Name", "HasPPC" },
            { "Name", "HitPPC" },
            { "Name", "LEG1KPI" },
            { "Name", "LEG2KPI" },
            { "Name", "LEG3KPI" },
            { "Name", "LEG4KPI" },
            { "Name", "NotBC" },
            { "Name", "PCG" },
            { "Name", "PCG90" },
            { "Name", "PCGCKPI" },
            { "Name", "PCS" },
            { "Name", "PCS90" },
            { "Name", "PCSCKPI" },
            { "Name", "PPCKPI" },
            { "Name", "PPV4KPI" },
            { "Name", "PPVKPI" },
            { "Name", "PV4KPI" },
            { "Name", "PV90KPI" },
            { "Name", "PVKPI" },
            { "Name", "Qual" },
            { "Name", "R10" },
            { "Name", "R100" },
            { "Name", "R20" },
            { "Name", "R30" },
            { "Name", "R40" },
            { "Name", "R50" },
            { "Name", "R60" },
            { "Name", "R70" },
            { "Name", "R80" },
            { "Name", "R90" },
            { "RC", "RC" },
            { "Name", "RC90" },
            { "Name", "RCCKPI" },
            { "Name", "SDRUP" },
            { "Name", "SVPLBP" },
            { "Name", "SVPRUP" },
            { "Name", "ViewAll" },
            { "Name", "VPLBP" },
            { "Name", "VPRUP" },
            { "Name", "WB100" },
            { "Name", "WB1200" },
            { "Name", "WB1550" },
            { "Name", "WB2250" },
            { "Name", "WB275" },
            { "Name", "WB4200" },
            { "Name", "WB525" },
            { "Name", "WB6875" },
            { "Name", "WB850" }
        };
    }

}
